/* Generated by cbindgen - DO NOT EDIT */

#ifndef TANTIVY_MOBILE_H
#define TANTIVY_MOBILE_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Search result structure */
typedef struct {
    char* id;
    char* title;
    char* category;
    char* summary;
    uint64_t priority;
    float score;
} SearchResult;

/* Search results container */
typedef struct {
    SearchResult* results;
    size_t count;
    uint64_t search_time_ms;
} SearchResults;

/* Index statistics */
typedef struct {
    uint64_t num_docs;
    uint64_t index_size_bytes;
} IndexStats;

/* Initialize logging for mobile platforms */
void tantivy_init_logging(void);

/* Create a new index with PrepperApp schema */
void* tantivy_create_index(const char* path);

/* Open an existing index */
void* tantivy_open_index(const char* path);

/* Add a document to the index */
int32_t tantivy_add_document(
    void* index_ptr,
    const char* id,
    const char* title,
    const char* category,
    uint64_t priority,
    const char* summary,
    const char* content
);

/* Commit changes to the index */
int32_t tantivy_commit(void* index_ptr);

/* Search the index */
SearchResults* tantivy_search(
    void* index_ptr,
    const char* query,
    size_t limit
);

/* Free search results */
void tantivy_free_search_results(SearchResults* results);

/* Free an index manager */
void tantivy_free_index(void* index_ptr);

/* Get index statistics */
IndexStats tantivy_get_index_stats(void* index_ptr);

/* Error codes */
#define TANTIVY_SUCCESS 0
#define TANTIVY_ERROR_INVALID_PARAM -1
#define TANTIVY_ERROR_INDEX_CREATION -2
#define TANTIVY_ERROR_SEARCH_FAILED -3
#define TANTIVY_ERROR_INDEXING_FAILED -4

#ifdef __cplusplus
}
#endif

#endif /* TANTIVY_MOBILE_H */